name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: The use case first — what are you trying to do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
